apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capv-pvc
spec:
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 5Gi
  storageClassName: vsphere-csi